#!/bin/bash
echo SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID >> .env
echo SPOTIFY_REDIRECT_URL=$SPOTIFY_REDIRECT_URL >> .env
echo SPOTIFY_TOKEN_REFRESH_URL=$SPOTIFY_TOKEN_REFRESH_URL >> .env
echo SPOTIFY_TOKEN_SWAP_URL=$SPOTIFY_TOKEN_SWAP_URL >> .env
echo REVENUE_CAT_IOS_KEY=$REVENUE_CAT_IOS_KEY >> .env
echo REVENUE_CAT_ANDROID_KEY=$REVENUE_CAT_ANDROID_KEY >> .env
echo FACEBOOK_APP_ID=$FACEBOOK_APP_ID >> .env
echo INSTABUG_DEV_TOKEN=$INSTABUG_DEV_TOKEN >> .env
echo INSTABUG_PROD_TOKEN=$INSTABUG_PROD_TOKEN >> .env
echo -n FACEBOOK_CLIENT_TOKEN=$FACEBOOK_CLIENT_TOKEN >> .env