#!/bin/bash
echo REVENUE_CAT_IOS_KEY=$REVENUE_CAT_IOS_KEY >> .env
echo REVENUE_CAT_ANDROID_KEY=$REVENUE_CAT_ANDROID_KEY >> .env
echo FACEBOOK_APP_ID=$FACEBOOK_APP_ID >> .env
echo INSTABUG_DEV_TOKEN=$INSTABUG_DEV_TOKEN >> .env
echo INSTABUG_PROD_TOKEN=$INSTABUG_PROD_TOKEN >> .env
echo -n FACEBOOK_CLIENT_TOKEN=$FACEBOOK_CLIENT_TOKEN >> .env