# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
$RNFirebaseAsStaticFramework = true

target 'HealthAndMovement' do
  use_frameworks! :linkage => :static

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    pre_install do |installer|
      installer.pod_targets.each do |pod|
        if pod.name.eql?('react-native-document-picker')
          def pod.build_type
          Pod::BuildType.static_library
        end
      end
    end
  end
  
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings["DEVELOPMENT_TEAM"] = "27RJG57PEM"
           end
      end
    end
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  
    # Modify RCT-Folly Portability.h to disable coroutines
    Dir.glob(installer.sandbox.root + "RCT-Folly/folly/Portability.h") do |file|
      begin
        # First try to make the file writable
        system "chmod +w #{file}"
        
        contents = File.read(file)
        modified_contents = contents.gsub(/#define FOLLY_HAS_COROUTINES 1/, '#define FOLLY_HAS_COROUTINES 0')
        
        # Try writing with elevated privileges if needed
        if !File.writable?(file)
          system "sudo chmod +w #{file}"
        end
        
        File.write(file, modified_contents)
        
        # Optionally restore original permissions
        system "chmod -w #{file}"
      rescue => e
        Pod::UI.warn "Failed to modify Portability.h: #{e.message}"
      end
    end
  end
end
