name: Deploy android to firebase
on:
  push:
    branches:
      - firebase
jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Run tests
        run: |
          yarn test
      # - name: Create sentry files
      #   env:
      #     SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      #   run: |
      #     exec .github/scripts/create-sentry-files.sh
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{github.run_number}}
      - name: Build android apk
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          exec .github/scripts/assemble-release.sh
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: internal
          file: android/app/build/outputs/apk/release/app-release.apk
